#!/usr/bin/env sh

# Recent versions of MacOS support OFD locks, but golang.org/x/sys/unix doesn't
# have the proper constants for them. Generate them using the system headers.
# Based on golang.org/x/sys/unix/mkerrors.sh

INCLUDES='
#include <fcntl.h>
'

# Using cgo to convert #define macros to Go constants
cat > _const.go << EOF
package store

/*$INCLUDES*/
import "C"

const (
$(
    echo "$INCLUDES" | "${CC:-cc}" -x c - -E -dM | \
        grep '^#define F_OFD_' | \
        sed 's/^#define \([A-Z_]*\) .*/\t\1 = C.\1/'
)
)
EOF

cat > zconstants_darwin.go << EOF
// Code generated by mkconstants_darwin.sh; DO NOT EDIT.

$(go tool cgo -godefs _const.go | tail -n +3 | gofmt)
EOF

rm -f _const.go
rm -rf _obj

echo "Generated zconstants_darwin.go"
