load("//:rules.bzl", "executable_file")

genrule(
    name = "version",
    out = "VERSION",
    cmd = "$(exe :generate_version) > $OUT",
    visibility = ["PUBLIC"],
)

executable_file(
    name = "generate_version",
    src = "generate_version.sh",
)
