excludes = ["LICENSE*", "README.md"]

walk = "jujutsu"

[formatter.buildifier]
command = "buildifier"
includes = ["**/BUCK", "**/PACKAGE", "*.bzl"]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.ruff-format]
command = "ruff"
includes = ["*.py", "*.pyi"]
options = ["format"]

[formatter.swift]
command = "swift"
includes = ["*.swift"]
options = ["format", "-i"]
