excludes = [
    "LICENSE*",
    "README.md",
    "toolchains/apple/third-party/prelude/**",
]

walk = "jujutsu"

[formatter.buildifier]
command = "buildifier"
includes = ["**/BUCK", "**/PACKAGE", "*.bzl"]

[formatter.deno]
command = "buck2"
includes = ["*.js", "*.ts"]
options = ["run", "toolchains//deno:binary", "--", "fmt"]

[formatter.fourmolu]
command = "fourmolu"
options = ["-i", "-c"]
includes = ["*.hs"]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.ruff-format]
command = "ruff"
includes = ["*.py", "*.pyi"]
options = ["format"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]
options = ["--config", "skip_children=true", "--edition", "2024"]

[formatter.swift]
command = "swift"
includes = ["*.swift"]
options = ["format", "-i"]
