excludes = ["LICENSE*", "README.md"]

walk = "jujutsu"

[formatter.buildifier]
command = "buildifier"
includes = ["**/BUCK", "**/PACKAGE", "*.bzl"]

[formatter.ruff-format]
command = "ruff"
includes = ["*.py", "*.pyi"]
options = ["format"]
