load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:no_toolchain.bzl", "no_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "cxx",
    actual = "toolchains//cxx:cxx",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "go_bootstrap",
    actual = "toolchains//go:go_bootstrap",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "go",
    actual = "toolchains//go:go",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "protobuf",
    actual = "toolchains//protobuf:protobuf",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "swift",
    actual = "toolchains//apple:swift",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "apple-default",
    actual = "toolchains//apple:apple",
    visibility = ["PUBLIC"],
)

no_toolchain(
    name = "apple-xctoolchain",
    visibility = ["PUBLIC"],
)

no_toolchain(
    name = "apple-xctoolchain-bundle-id",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)
