load(":defs.bzl", "typescript_toolchain")
load(":esbuild.bzl", "esbuild_bundler")

esbuild_bundler(
    name = "esbuild-bundler",
    esbuild = "//esbuild:binary",
    bundle = "//typescript/tools:esbuild_bundle",
)

typescript_toolchain(
    name = "typescript",
    tsc_build = "//typescript/tools:tsc_build",
    bundler = ":esbuild-bundler",
    visibility = ["toolchains//..."],
)
