load(":defs.bzl", "typescript_toolchain")
load(":esbuild.bzl", "esbuild_bundler")
load(":rolldown.bzl", "rolldown_bundler")

http_archive(
    name = "darwin-arm64-0.28.0.tgz",
    sha256 = "6ef1261e245caed64e4d5195572e3468f18a5df4b65df5e14f9ae10408ad5502",
    strip_prefix = "package",
    urls = ["https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.28.0.tgz"],
)

http_archive(
    name = "linux-x64-0.28.0.tgz",
    sha256 = "e94bf1c7f44197b22cf6a787578eca9af805aa9624104488252de2a765c6a4f0",
    strip_prefix = "package",
    urls = ["https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.28.0.tgz"],
)

genrule(
    name = "esbuild-aarch64-darwin",
    out = "esbuild",
    cmd = "ln -s $(location :darwin-arm64-0.28.0.tgz)/bin/esbuild $OUT",
    executable = True,
)

genrule(
    name = "esbuild-x86_64-linux",
    out = "esbuild",
    cmd = "ln -s $(location :linux-x64-0.28.0.tgz)/bin/esbuild $OUT",
    executable = True,
)

alias(
    name = "esbuild",
    actual = select({
        "config//os:linux": ":esbuild-x86_64-linux",
        "config//os:macos": ":esbuild-aarch64-darwin",
    }),
    visibility = ["PUBLIC"],
)

esbuild_bundler(
    name = "esbuild-bundler",
    esbuild = ":esbuild",
    bundle = "//typescript/tools:esbuild_bundle",
)

rolldown_bundler(
    name = "rolldown-bundler",
    bundle = "//typescript/tools:rolldown_bundle",
)

constraint(
    name = "bundler",
    default = "rolldown",
    values = [
        "esbuild",
        "rolldown",
    ],
)

alias(
    name = "oxfmt",
    actual = "//typescript/tools:oxfmt",
    visibility = ["PUBLIC"],
)

alias(
    name = "oxlint",
    actual = "//typescript/tools:oxlint",
    visibility = ["PUBLIC"],
)

typescript_toolchain(
    name = "typescript",
    tsc_build = "//typescript/tools:tsc_build",
    bundler = select({
        ":bundler[esbuild]": ":esbuild-bundler",
        ":bundler[rolldown]": ":rolldown-bundler",
    }),
    visibility = ["toolchains//..."],
)
