#!/usr/bin/env python3

"""Generate BUCK files for third-party Go dependencies.

This is a simple Python script that's roughly equivalent to the `gobuckify`
tool from the Buck2 prelude. One notable difference is that dependencies are
downloaded with `prelude.http_archive` instead of with `go mod vendor`.
"""

import argparse
import hashlib
import io
import json
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path


def discover_packages(tags: list[str]) -> list[dict]:
    cmd = ["go", "list", "-json", "-deps"]
    if tags:
        cmd.append(f"-tags={','.join(tags)}")

    package_list = subprocess.check_output(
        cmd,
        text=True,
    ).strip()
    mod_path = subprocess.check_output(
        ["go", "list", "-m", "-f", "{{.Dir}}"],
        text=True,
    ).strip()

    main_module = None
    if (go_mod := Path(mod_path) / "go.mod").exists():
        for line in go_mod.read_text().splitlines():
            if line.startswith("module "):
                main_module = line.split()[1]
                break

    packages = []
    decoder = json.JSONDecoder()
    while package_list:
        pkg, end = decoder.raw_decode(package_list)
        package_list = package_list[end:].lstrip()

        import_path = pkg.get("ImportPath", "")
        module = pkg.get("Module")
        if (
            pkg.get("Standard", False)
            or module is None
            or import_path == main_module
            or (main_module is not None and import_path.startswith(main_module + "/"))
        ):
            continue

        module_path = module["Path"]
        relative_path = import_path.removeprefix(module_path).lstrip("/") or "."
        if relative_path != "." and not import_path.startswith(module_path + "/"):
            continue

        packages.append(
            {
                "import_path": import_path,
                "module_path": module_path,
                "module_version": module.get("Version", ""),
                "relative_path": relative_path,
                "imports": pkg.get("Imports", []),
                "embed_files": pkg.get("EmbedFiles", []),
            }
        )

    return packages


def fetch_module_metadata(mod_path: str, module: dict) -> None:
    # escape upper case letters with the ! escaping scheme
    escaped = "".join(f"!{c.lower()}" if c.isupper() else c for c in mod_path)
    version = module["version"]
    url = f"https://proxy.golang.org/{escaped}/@v/{version}.zip"
    print(f"Downloading module {mod_path} {version}", file=sys.stderr)
    with urllib.request.urlopen(url) as response:
        data = response.read()

    # store sha256 for http_archive
    module["sha256"] = hashlib.sha256(data).hexdigest()

    # collect embedded files
    embed_files = {
        rel: set(pkg["embed_files"]) for rel, pkg in module["packages"].items()
    }

    # expose all non-test .go, .h, and .s files (not just the ones mentioned by
    # go list) to simplify cross-compilation
    prefix = f"{mod_path}@{version}/"
    zip_files: dict[str, list[str]] = {}
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        for name in zf.namelist():
            if not name.startswith(prefix) or name.endswith("/"):
                continue
            rel_path = name[len(prefix) :]
            pkg_dir, _, filename = rel_path.rpartition("/")
            pkg_dir = pkg_dir or "."

            if pkg_dir not in module["packages"]:
                continue
            is_go_src = filename.endswith(".go") and not filename.endswith("_test.go")
            is_asm_src = filename.endswith(".h") or filename.endswith(".s")
            if is_go_src or is_asm_src or filename in embed_files.get(pkg_dir, set()):
                if pkg_dir not in zip_files:
                    zip_files[pkg_dir] = []
                zip_files[pkg_dir].append(rel_path)
    module["zip_files"] = {pkg: sorted(files) for pkg, files in zip_files.items()}


def generate_buck(
    modules: dict[str, dict], packages: list[dict], visibility: str
) -> str:
    buck = "# generated by gobuckify-mini\n"
    all_import_paths = {pkg["import_path"] for pkg in packages}

    for mod_path in sorted(modules):
        mod = modules[mod_path]
        version = mod["version"]

        # http_archive for the module
        buck += f"""
http_archive(
    name = "{mod_path}__srcs",
    sha256 = "{mod["sha256"]}",
    strip_prefix = "{mod_path}@{version}",
    sub_targets = {{"""
        for pkg_dir in sorted(mod["zip_files"]):
            buck += f"""
        "{pkg_dir}": ["""
            for f in mod["zip_files"][pkg_dir]:
                buck += f"""
            "{f}","""
            buck += """
        ],"""
        buck += f"""
    }},
    urls = ["https://proxy.golang.org/{mod_path}/@v/{version}.zip"],
)
"""

        # go_library for each package in this module
        for rel in sorted(mod["packages"]):
            pkg = mod["packages"][rel]
            src_ref = f":{mod_path}__srcs[{rel}]"
            deps = sorted(imp for imp in pkg["imports"] if imp in all_import_paths)

            buck += f"""
go_library(
    name = "{pkg["import_path"]}",
    package_name = "{pkg["import_path"]}",
    srcs = ["{src_ref}"],"""
            if pkg["embed_files"]:
                buck += f"""
    embed_srcs = [
        "{src_ref}",
    ],"""
            buck += f"""
    visibility = ["{visibility}"],"""
            if deps:
                buck += """
    deps = ["""
                for dep in deps:
                    buck += f"""
        ":{dep}","""
                buck += """
    ],"""
            buck += """
)
"""

    return buck


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate BUCK file for third-party Go dependencies"
    )
    parser.add_argument(
        "--visibility",
        default="PUBLIC",
        help="Package visibility for third-party libraries",
    )
    parser.add_argument(
        "--output", nargs="?", const="BUCK", default="-", help="Write output to a file"
    )
    parser.add_argument(
        "--tags",
        default=[],
        action="append",
        help="Build tags to pass to go list",
    )
    args = parser.parse_args()

    packages = discover_packages(args.tags)
    if not packages:
        print("No third-party packages found. Nothing to generate.", file=sys.stderr)
        sys.exit(0)
    else:
        print(f"Found {len(packages)} third-party packages", file=sys.stderr)

    modules: dict[str, dict] = {}
    for pkg in packages:
        if pkg["module_path"] not in modules:
            modules[pkg["module_path"]] = {
                "version": pkg["module_version"],
                "packages": {},
            }
        modules[pkg["module_path"]]["packages"][pkg["relative_path"]] = pkg
    for mod_path, mod in modules.items():
        fetch_module_metadata(mod_path, mod)
    print(f"Grouped into {len(modules)} modules", file=sys.stderr)

    buck_content = generate_buck(modules, packages, args.visibility)

    if args.output == "-":
        print(buck_content)
    else:
        Path(args.output).write_text(buck_content, encoding="utf-8")
        print(f"Wrote dependencies to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
