load("//deno:rules.bzl", "deno_binary")

deno_binary(
    name = "esbuild_bundle",
    main = "esbuild_bundle.ts",
    srcs = ["lib/util.ts", "lib/types.ts"],
    permissions = ["env", "read", "run", "write"],
    npm_deps = ["root//third-party/npm/esbuild:esbuild"],
    visibility = ["//typescript/..."],
)

deno_binary(
    name = "oxfmt",
    main = "oxfmt.ts",
    skip_check = True,
    permissions = ["env", "ffi", "read", "run", "sys", "write"],
    npm_deps = ["root//third-party/npm/oxfmt:oxfmt"],
    visibility = ["PUBLIC"],
)

deno_binary(
    name = "rolldown_bundle",
    main = "rolldown_bundle.ts",
    srcs = ["lib/util.ts", "lib/types.ts"],
    permissions = ["env", "ffi", "read", "run", "write"],
    npm_deps = ["root//third-party/npm/rolldown:rolldown"],
    visibility = ["//typescript/..."],
)

deno_binary(
    name = "tsc_build",
    main = "tsc_build.ts",
    srcs = ["lib/util.ts", "lib/types.ts"],
    permissions = ["env", "read", "sys", "write"],
    npm_deps = ["root//third-party/npm/typescript:typescript"],
    visibility = ["//typescript/..."],
)
