load(":defs.bzl", "wasm_toolchain")

http_archive(
    name = "binaryen-version_129-arm64-macos.tar.gz",
    sha256 = "d1bb014775ca3002506712b81b4406d126ff6845e8b2f343bc2696a1a88b7117",
    strip_prefix = "binaryen-version_129",
    urls = ["https://github.com/WebAssembly/binaryen/releases/download/version_129/binaryen-version_129-arm64-macos.tar.gz"],
)

http_archive(
    name = "binaryen-version_129-x86_64-linux.tar.gz",
    sha256 = "50b9fa62b9abea752da92ec57e0c555fee578760cd237c40107957715d2976ba",
    strip_prefix = "binaryen-version_129",
    urls = ["https://github.com/WebAssembly/binaryen/releases/download/version_129/binaryen-version_129-x86_64-linux.tar.gz"],
)

genrule(
    name = "wasm-opt-arm64-macos",
    out = "wasm-opt",
    cmd = "ln -sF $(location :binaryen-version_129-arm64-macos.tar.gz)/bin/wasm-opt $OUT",
    executable = True,
)

genrule(
    name = "wasm-opt-x86_64-linux",
    out = "wasm-opt",
    cmd = "ln -sF $(location :binaryen-version_129-x86_64-linux.tar.gz)/bin/wasm-opt $OUT",
    executable = True,
)

wasm_toolchain(
    name = "wasm",
    wasm_opt = select({
        "config//os:linux": ":wasm-opt-x86_64-linux",
        "config//os:macos": ":wasm-opt-arm64-macos",
    }),
    visibility = ["toolchains//..."],
)
