load(":defs.bzl", "wasm_toolchain")

http_archive(
    name = "binaryen-version_129-arm64-macos.tar.gz",
    sha256 = "d1bb014775ca3002506712b81b4406d126ff6845e8b2f343bc2696a1a88b7117",
    strip_prefix = "binaryen-version_129",
    urls = ["https://github.com/WebAssembly/binaryen/releases/download/version_129/binaryen-version_129-arm64-macos.tar.gz"],
)

http_archive(
    name = "binaryen-version_129-x86_64-linux.tar.gz",
    sha256 = "50b9fa62b9abea752da92ec57e0c555fee578760cd237c40107957715d2976ba",
    strip_prefix = "binaryen-version_129",
    urls = ["https://github.com/WebAssembly/binaryen/releases/download/version_129/binaryen-version_129-x86_64-linux.tar.gz"],
)

genrule(
    name = "wasm-opt-arm64-macos",
    out = "wasm-opt",
    cmd = "ln -s $(location :binaryen-version_129-arm64-macos.tar.gz)/bin/wasm-opt $OUT",
    executable = True,
)

genrule(
    name = "wasm-opt-x86_64-linux",
    out = "wasm-opt",
    cmd = "ln -s $(location :binaryen-version_129-x86_64-linux.tar.gz)/bin/wasm-opt $OUT",
    executable = True,
)

http_archive(
    name = "wasm-tools-1.252.0-aarch64-macos.tar.gz",
    sha256 = "c4c0f8560d996e47313aadf8df745e4d15eef38090e671384eafcb06d8d135fa",
    strip_prefix = "wasm-tools-1.252.0-aarch64-macos",
    urls = ["https://github.com/bytecodealliance/wasm-tools/releases/download/v1.252.0/wasm-tools-1.252.0-aarch64-macos.tar.gz"],
)

http_archive(
    name = "wasm-tools-1.252.0-x86_64-linux.tar.gz",
    sha256 = "097b1181d5b2bc3f2ebc44b4e72edf18308902023f1f1483a1a7dc1268ea988d",
    strip_prefix = "wasm-tools-1.252.0-x86_64-linux",
    urls = ["https://github.com/bytecodealliance/wasm-tools/releases/download/v1.252.0/wasm-tools-1.252.0-x86_64-linux.tar.gz"],
)

genrule(
    name = "wasm-tools-arm64-macos",
    out = "wasm-tools",
    cmd = "ln -s $(location :wasm-tools-1.252.0-aarch64-macos.tar.gz)/wasm-tools $OUT",
    executable = True,
)

genrule(
    name = "wasm-tools-x86_64-linux",
    out = "wasm-tools",
    cmd = "ln -s $(location :wasm-tools-1.252.0-x86_64-linux.tar.gz)/wasm-tools $OUT",
    executable = True,
)

http_file(
    name = "wasi-snapshot-preview1-reactor-v46.0.1",
    out = "wasi_snapshot_preview1.reactor.wasm",
    urls = ["https://github.com/bytecodealliance/wasmtime/releases/download/v46.0.1/wasi_snapshot_preview1.reactor.wasm"],
    sha256 = "0acb10959bd3c1d2e7903ef82212910bfc156ab5698ef3f2ff669474ba59fb0a",
)

alias(
    name = "wasi-snapshot-preview1-reactor-adapter",
    actual = ":wasi-snapshot-preview1-reactor-v46.0.1",
    visibility = ["PUBLIC"],
)

wasm_toolchain(
    name = "wasm",
    wasm_opt = select({
        "config//os:linux": ":wasm-opt-x86_64-linux",
        "config//os:macos": ":wasm-opt-arm64-macos",
    }),
    wasm_tools = select({
        "config//os:linux": ":wasm-tools-x86_64-linux",
        "config//os:macos": ":wasm-tools-arm64-macos",
    }),
    visibility = ["toolchains//..."],
)
