load(":pkgs.bzl", "BOOT_MANIFESTS")

[
    alias(
        name = pkg["name"],
        actual = "//haskell:ghc[{}]".format(pkg["name"]),
        visibility = ["PUBLIC"],
    )
    # NOTE: this assumes all distributions have the same set of packages
    for pkg in BOOT_MANIFESTS.values()[0]["package"]
]
