#!/usr/bin/env python3

import subprocess
import sys
from pathlib import Path

PLATFORMS = {
    "config//os:linux": "x86_64-ubuntu20_04-linux",
    "config//os:macos": "aarch64-apple-darwin",
}
LIB_PREFIXES = {
    "config//os:linux": "x86_64-linux-ghc",
    "config//os:macos": "aarch64-osx-ghc",
}
EXTS = {
    "config//os:linux": "so",
    "config//os:macos": "dylib",
}


def locate_root_db(target: str) -> str:
    root = subprocess.check_output(
        ["buck2", "build", target, "--show-output"],
        text=True,
    ).removeprefix(target + " ")
    return root.rstrip() + "/lib/package.conf.d"


def list_packages(db: str) -> list[str]:
    return (
        subprocess.check_output(
            [
                "ghc-pkg",
                "--package-db",
                db,
                "list",
                "--names-only",
                "--simple-output",
            ],
            text=True,
        )
        .rstrip()
        .split(" ")
    )


def package_field_raw(package: str, field: str, db) -> str | None:
    field = subprocess.check_output(
        [
            "ghc-pkg",
            "--package-db",
            db,
            "field",
            package,
            field,
            "--simple-output",
        ],
        text=True,
    ).rstrip()
    if field:
        return field
    else:
        return None


def id_to_name(id: str) -> str:
    for i, c in enumerate(id):
        if c == "-" and len(id) > i + 1 and id[i + 1].isdigit():
            return id[:i]
    return id


def main() -> None:
    version = sys.argv[1]

    buck = """# @generated by `gen_pkgs.py`

load("@root//tools/reflink:defs.bzl", "reflink_project")
load("//haskell:defs.bzl", "haskell_prebuilt_library")
"""

    dbs = {}
    packages = []
    ids = {}
    lib_paths = {}
    shared_libs = {}
    static_libs = {}
    import_dirs = {}
    for name, dist in PLATFORMS.items():
        lib_paths[name] = f"ghc-{version}-{dist}-libs"
        target = f"toolchains//haskell:ghc-{version}-{dist}.tar.xz"
        dbs[name] = locate_root_db(target)
        buck += f"""
reflink_project(
    name = "{lib_paths[name]}",
    dir = "{target}",
    sub_targets = ["""
        if not packages:
            packages = list_packages(dbs[name])
        ids[name] = {
            package: package_field_raw(package, "id", dbs[name]) for package in packages
        }
        lib_prefix = f"lib/{LIB_PREFIXES[name]}-{version}"
        shared_libs[name] = {}
        static_libs[name] = {}
        import_dirs[name] = {}
        buck += """
        "lib/package.conf.d","""
        for package in packages:
            shared_libs[name][package] = (
                f"{lib_prefix}/libHS{ids[name][package]}-ghc{version}.{EXTS[name]}"
            )
            buck += f"""
        "{shared_libs[name][package]}","""
        for package in packages:
            import_dirs[name][package] = f"{lib_prefix}/{ids[name][package]}"
            static_libs[name][package] = (
                f"{import_dirs[name][package]}/libHS{ids[name][package]}.a"
            )
            buck += f"""
        "{static_libs[name][package]}","""
        for package in packages:
            buck += f"""
        "{import_dirs[name][package]}","""
        buck += """
    ],
)
"""
    default_db = next(iter(dbs.values()))

    for package in packages:
        pkg_version = package_field_raw(package, "version", default_db)
        pkg_depends = package_field_raw(package, "depends", default_db)

        buck += f"""
haskell_prebuilt_library(
    name = "{package}",
    db = select({{"""
        for name in PLATFORMS:
            buck += f"""
        "{name}": ":{lib_paths[name]}[lib/package.conf.d]","""
        buck += """
    }),
    id = select({"""
        for name in PLATFORMS:
            buck += f"""
        "{name}": "{ids[name][package]}","""
        buck += """
    }),
    shared_libs = select({"""
        for name in PLATFORMS:
            buck += f"""
        "{name}": {{
            "{Path(shared_libs[name][package]).name}": ":{lib_paths[name]}[{shared_libs[name][package]}]",
        }},"""
        buck += """
    }),
    static_libs = select({"""
        for name in PLATFORMS:
            buck += f"""
        "{name}": [":{lib_paths[name]}[{static_libs[name][package]}]"],"""
        buck += """
    }),
    import_dirs = select({"""
        for name in PLATFORMS:
            buck += f"""
        "{name}": [":{lib_paths[name]}[{import_dirs[name][package]}]"],"""
        buck += f"""
    }}),
    version = "{pkg_version}","""
        if pkg_depends:
            buck += """
    deps = ["""
            for dep in pkg_depends.split(" "):
                buck += f"""
        ":{id_to_name(dep)}","""
            buck += """
    ],"""
        buck += """
    visibility = ["PUBLIC"],
)
"""

    print(buck, end="")


if __name__ == "__main__":
    main()
