#!/usr/bin/env python3

import subprocess
import sys


def locate_root_db(target: str) -> str:
    root = subprocess.check_output(
        ["buck2", "build", target, "--show-output"],
        text=True,
    ).removeprefix(target + " ")
    return root.rstrip() + "/lib/package.conf.d"


def list_packages(db: str) -> list[str]:
    return (
        subprocess.check_output(
            [
                "ghc-pkg",
                "--package-db",
                db,
                "list",
                "--names-only",
                "--simple-output",
            ],
            text=True,
        )
        .rstrip()
        .split(" ")
    )


def package_field_raw(package: str, field: str, db) -> str | None:
    field = subprocess.check_output(
        [
            "ghc-pkg",
            "--package-db",
            db,
            "field",
            package,
            field,
            "--simple-output",
        ],
        text=True,
    ).rstrip()
    if field:
        return field
    else:
        return None


def main() -> None:
    target = sys.argv[1]

    pkg_db = """# @generated by `gen_pkgs.py`
"""

    db = locate_root_db(target)
    packages = list_packages(db)

    data_dir = next(
        (
            package_field_raw(package, "data-dir", db)
            for package in packages
            if package == "rts"
        ),
        None,
    )
    if data_dir and data_dir.startswith("${pkgroot}/../share/"):
        lib_prefix, _, _ = data_dir.removeprefix("${pkgroot}/../share/").partition("/")
        pkg_db += f"""
lib_prefix = "{lib_prefix}"
"""
    else:
        raise RuntimeError("could not determine data-dir of rts package")

    for package in packages:
        pkg_id = package_field_raw(package, "id", db)
        pkg_version = package_field_raw(package, "version", db)
        pkg_hs_libraries = package_field_raw(package, "hs-libraries", db)
        pkg_depends = package_field_raw(package, "depends", db)

        pkg_db += f"""
[[package]]
name = "{package}"
id = "{pkg_id}"
version = "{pkg_version}"
"""
        if not pkg_hs_libraries:
            pkg_db += """virtual = true
"""
        pkg_db += """depends = ["""
        if pkg_depends:
            for dep in pkg_depends.split(" "):
                pkg_db += f"""
  "{dep}","""
            pkg_db += """
"""
        pkg_db += """]
"""

    print(pkg_db, end="")


if __name__ == "__main__":
    main()
