load("//typescript:esbuild.bzl", "esbuild_bundler")
load(":defs.bzl", "esbuild_toolchain")

http_archive(
    name = "darwin-arm64-0.28.0.tgz",
    sha256 = "6ef1261e245caed64e4d5195572e3468f18a5df4b65df5e14f9ae10408ad5502",
    strip_prefix = "package",
    urls = ["https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.28.0.tgz"],
)

http_archive(
    name = "linux-x64-0.28.0.tgz",
    sha256 = "e94bf1c7f44197b22cf6a787578eca9af805aa9624104488252de2a765c6a4f0",
    strip_prefix = "package",
    urls = ["https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.28.0.tgz"],
)

genrule(
    name = "esbuild-aarch64-darwin",
    out = "esbuild",
    cmd = "ln -sF $(location :darwin-arm64-0.28.0.tgz)/bin/esbuild $OUT",
    executable = True,
)

genrule(
    name = "esbuild-x86_64-linux",
    out = "esbuild",
    cmd = "ln -sF $(location :linux-x64-0.28.0.tgz)/bin/esbuild $OUT",
    executable = True,
)

esbuild_bundler(
    name = "bundler",
    esbuild = select({
        "config//os:linux": ":esbuild-x86_64-linux",
        "config//os:macos": ":esbuild-aarch64-darwin",
    }),
    bundle = "//typescript/tools:esbuild_bundle",
    visibility = ["toolchains//..."],
)

esbuild_toolchain(
    name = "esbuild",
    esbuild = select({
        "config//os:linux": ":esbuild-x86_64-linux",
        "config//os:macos": ":esbuild-aarch64-darwin",
    }),
    esbuild_build = "//esbuild/tools:esbuild_build",
    visibility = ["toolchains//..."],
)
