load("@toolchains//esbuild:rules.bzl", "esbuild_bundle")
load("@toolchains//typescript:rules.bzl", "typescript_bundle")
load(":defs.bzl", "css_stylesheet")

TARGETS = ["chrome142", "firefox140", "safari18", "ios18"]

export_file(
    name = "index",
    src = "index.html",
    visibility = ["//remote/..."],
)

css_stylesheet(
    name = "xterm-css",
    package = "//third-party/npm/@xterm/xterm:xterm",
    path = "css/xterm.css",
)

typescript_bundle(
    name = "bundle-js",
    main = "app.ts",
    deps = [
        ":xterm-css",
        "//third-party/npm/@xterm/xterm:xterm",
    ],
    lib = ["esnext", "dom", "dom.iterable"],
    format = "esm",
    platform = "browser",
    target = TARGETS,
    minify = True,
    visibility = ["//remote/..."],
)

esbuild_bundle(
    name = "bundle-css",
    entrypoints = ["main.css"],
    outfile = "main.css",
    deps = ["//third-party/npm/@xterm/xterm:xterm"],
    target = TARGETS,
    minify = True,
    visibility = ["//remote/..."],
)
