load("//haskell/lib/pkgs.bzl", "BOOT_MANIFESTS")
load(":defs.bzl", "exec_alias", "haskell_ghc_distr", "haskell_toolchain")
load(":wasm.bzl", "haskell_ghc_wasm_distr", "wasi_sdk_binary")

http_archive(
    name = "ghc-9.10.3-x86_64-ubuntu20_04-linux.tar.xz",
    sha256 = "b6200c32a56f26f5d2ff77c92481a47a53bb3d43cbc82b59a997aed2ad5fd937",
    strip_prefix = "ghc-9.10.3-x86_64-unknown-linux",
    urls = ["https://downloads.haskell.org/~ghc/9.10.3/ghc-9.10.3-x86_64-ubuntu20_04-linux.tar.xz"],
)

http_archive(
    name = "ghc-9.10.3-aarch64-apple-darwin.tar.xz",
    sha256 = "9f50ddd87be5cb994c719402778d6c7fdd341934fd4fbc0fcc3ecb40d49f860c",
    strip_prefix = "ghc-9.10.3-aarch64-apple-darwin",
    urls = ["https://downloads.haskell.org/~ghc/9.10.3/ghc-9.10.3-aarch64-apple-darwin.tar.xz"],
)

haskell_ghc_distr(
    name = "ghc-9.10.3-x86_64-ubuntu20_04-linux",
    ghc_root = ":ghc-9.10.3-x86_64-ubuntu20_04-linux.tar.xz",
    target = "x86_64-ubuntu20_04-linux",
    host = "x86_64-ubuntu20_04-linux",
    version = "9.10.3",
    package_manifest = BOOT_MANIFESTS["ghc-9.10.3-x86_64-ubuntu20_04-linux"],
)

haskell_ghc_distr(
    name = "ghc-9.10.3-aarch64-apple-darwin",
    ghc_root = ":ghc-9.10.3-aarch64-apple-darwin.tar.xz",
    target = "aarch64-apple-darwin",
    host = "aarch64-apple-darwin",
    version = "9.10.3",
    package_manifest = BOOT_MANIFESTS["ghc-9.10.3-aarch64-apple-darwin"],
)

alias(
    name = "ghc-9.10.3",
    actual = select({
        "config//cpu:x86_64": select({
            "config//os:linux": ":ghc-9.10.3-x86_64-ubuntu20_04-linux",
        }),
        "config//cpu:arm64": select({
            "config//os:macos": ":ghc-9.10.3-aarch64-apple-darwin",
        }),
    }),
)

http_archive(
    name = "wasm32-wasi-ghc-9.10.tar.xz",
    sha256 = "60d0e537548a82590fd6cfd6eaec5ceba0bc58bf320a6f491843a1cf4403bce8",
    strip_prefix = "ghc-9.10.3.20260403-wasm32-wasi",
    urls = ["https://github.com/haskell-wasm/ghc-wasm-bindists/releases/download/20260403T135157/wasm32-wasi-ghc-9.10.tar.xz"],
)

http_archive(
    name = "wasm32-wasi-ghc-gmp-aarch64-darwin-9.10.tar.xz",
    sha256 = "3bda3333b3b09c99495a5513cf554d155d9462697a919919320ddac516496f0c",
    strip_prefix = "ghc-9.10.3.20260403-wasm32-wasi",
    urls = ["https://github.com/haskell-wasm/ghc-wasm-bindists/releases/download/20260403T135157/wasm32-wasi-ghc-gmp-aarch64-darwin-9.10.tar.xz"],
)

http_archive(
    name = "wasi-sdk-x86_64-linux.tar.gz",
    sha256 = "fa1b236d847fa6ab5abecb08b8c1807178818f68b33029845eb15157d5bdbe47",
    strip_prefix = "wasi-sdk-29.0-x86_64-linux",
    urls = ["https://github.com/haskell-wasm/ghc-wasm-bindists/releases/download/20251219T213239/wasi-sdk.tar.gz"],
)

http_archive(
    name = "wasi-sdk-aarch64-darwin.tar.gz",
    sha256 = "fcd80b74af20c8f4f2f9783852620db8e80ed7cf3fd162e760018819fa7de2ba",
    strip_prefix = "wasi-sdk-29.0-arm64-macos",
    urls = ["https://github.com/haskell-wasm/ghc-wasm-bindists/releases/download/20251219T213239/wasi-sdk-aarch64-darwin.tar.gz"],
)

http_archive(
    name = "libffi-wasm",
    sha256 = "526f4672ef732a5d29cc560bdd19809f2149a3338f295a2ad4d9d4da38a5234b",
    strip_prefix = "out/libffi-wasm",
    type = "zip",
    urls = ["https://github.com/haskell-wasm/ghc-wasm-bindists/releases/download/20250310T060803/libffi-wasm"],
)

[
    wasi_sdk_binary(
        name = "wasi-sdk-{}".format(name),
        sdk = select({
            "config//cpu:x86_64": select({
                "config//os:linux": ":wasi-sdk-x86_64-linux.tar.gz",
            }),
            "config//cpu:arm64": select({
                "config//os:macos": ":wasi-sdk-aarch64-darwin.tar.gz",
            }),
        }),
        binary = binary,
    )
    for name, binary in [
        ("wasm32-wasi-clang", "bin/wasm32-wasi-clang"),
        ("wasm32-wasi-clang++", "bin/wasm32-wasi-clang++"),
        ("wasm-ld", "bin/wasm-ld"),
        ("llvm-ar", "bin/llvm-ar"),
        ("llvm-ranlib", "bin/llvm-ranlib"),
        ("llvm-nm", "bin/llvm-nm"),
        ("llvm-objcopy", "bin/llvm-objcopy"),
        ("llvm-objdump", "bin/llvm-objdump"),
        ("llvm-strip", "bin/llvm-strip"),
    ]
]

cxx_toolchain(
    name = "cxx-wasm32-wasi-sdk",
    platform_name = "wasm32-wasi",
    compiler_type = "clang",
    c_compiler = ":wasi-sdk-wasm32-wasi-clang",
    c_compiler_type = "clang",
    c_compiler_flags = [
        "--target=wasm32-unknown-wasi",
        "-Wno-error=int-conversion",
        "-O3",
        "-mcpu=lime1",
        "-mreference-types",
        "-msimd128",
        "-Qunused-arguments",
        "-I$(location :libffi-wasm)/include",
    ],
    asm_compiler = ":wasi-sdk-wasm32-wasi-clang",
    assembler = ":wasi-sdk-wasm32-wasi-clang",
    cxx_compiler = ":wasi-sdk-wasm32-wasi-clang++",
    cxx_compiler_type = "clang",
    cxx_compiler_flags = [
        "--target=wasm32-unknown-wasi",
        "-fno-exceptions",
        "-Wno-error=int-conversion",
        "-O3",
        "-mcpu=lime1",
        "-mreference-types",
        "-msimd128",
        "-I$(location :libffi-wasm)/include",
    ],
    linker = ":wasi-sdk-wasm-ld",
    linker_flags = [
        "--target=wasm32-unknown-wasi",
        "-Wl,--error-limit=0,--keep-section=ghc_wasm_jsffi,--keep-section=target_features,--stack-first,--strip-debug",
        "-L$(location :libffi-wasm)/lib",
    ],
    linker_type = "gnu",
    split_debug_mode = "none",
    generate_linker_maps = False,
    archiver = ":wasi-sdk-llvm-ar",
    archiver_type = "gnu",  # prelude's Haskell rules don't support type "wasm"
    archiver_supports_argfiles = True,
    nm = ":wasi-sdk-llvm-nm",
    objcopy_for_shared_library_interface = ":wasi-sdk-llvm-objcopy",
    objdump = ":wasi-sdk-llvm-objdump",
    ranlib = ":wasi-sdk-llvm-ranlib",
    strip = ":wasi-sdk-llvm-strip",
    bolt = ":wasi-sdk-llvm-strip",
    object_file_extension = "o",
    static_library_extension = "a",
    visibility = ["PUBLIC"],
)

haskell_ghc_wasm_distr(
    name = "ghc-9.10.3.20260403-wasm32-wasi-x86_64-ubuntu20_04-linux",
    ghc_root = ":wasm32-wasi-ghc-9.10.tar.xz",
    cxx_toolchain = ":cxx-wasm32-wasi-sdk",
    bin_prefix = "wasm32-wasi-",
    host = "x86_64-ubuntu20_04-linux",
    version = "9.10.3.20260403",
    package_manifest = BOOT_MANIFESTS["ghc-9.10.3.20260403-wasm32-unknown-wasi"],
)

haskell_ghc_wasm_distr(
    name = "ghc-9.10.3.20260403-wasm32-wasi-aarch64-apple-darwin",
    ghc_root = ":wasm32-wasi-ghc-gmp-aarch64-darwin-9.10.tar.xz",
    cxx_toolchain = ":cxx-wasm32-wasi-sdk",
    bin_prefix = "wasm32-wasi-",
    host = "aarch64-apple-darwin",
    version = "9.10.3.20260403",
    package_manifest = BOOT_MANIFESTS["ghc-9.10.3.20260403-wasm32-unknown-wasi"],
)

alias(
    name = "ghc-9.10.3.20260403-wasm32-wasi",
    actual = select({
        "config//cpu:x86_64": select({
            "config//os:linux": ":ghc-9.10.3.20260403-wasm32-wasi-x86_64-ubuntu20_04-linux",
        }),
        "config//cpu:arm64": select({
            "config//os:macos": ":ghc-9.10.3.20260403-wasm32-wasi-aarch64-apple-darwin",
        }),
    }),
)

exec_alias(
    name = "ghc",
    actual = select({
        "config//os:wasi": ":ghc-9.10.3.20260403-wasm32-wasi",
        "DEFAULT": ":ghc-9.10.3",
    }),
    visibility = ["//haskell/..."],
)

haskell_toolchain(
    name = "haskell",
    ghc_distr = select({
        "config//os:wasi": ":ghc-9.10.3.20260403-wasm32-wasi",
        "DEFAULT": ":ghc-9.10.3",
    }),
    compiler_flags = ["-XGHC2024"],
    visibility = ["//..."],
)
