load(
    ":defs.bzl",
    "no_binary",
    "system_apple_toolchain",
    "system_swift_toolchain",
)

SDK_PATH = read_root_config(
    "apple",
    "sdk_path",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk",
)

PLATFORM_PATH = read_root_config(
    "apple",
    "platform_path",
    "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform",
)

no_binary(
    name = "no_binary",
)

# the same as prelude/apple/tools:apple-tools, but all tools that require
# Meta-internal things are stubbed out
apple_tools(
    name = "apple-tools",
    adhoc_codesign_tool = ":no_binary",
    assemble_bundle = ":no_binary",
    codesign_manifest_tree_postprocessor = "prelude//apple/tools/codesign_manifest_tree_postprocessor:codesign_manifest_tree_postprocessor",
    dry_codesign_tool = "prelude//apple/tools:dry_codesign_tool",
    framework_sanitizer = "prelude//apple/tools:framework_sanitizer",
    info_plist_processor = "prelude//apple/tools/info_plist_processor:tool",
    ipa_package_maker = "prelude//apple/tools:ipa_package_maker",
    make_modulemap = "prelude//apple/tools:make_modulemap",
    make_vfsoverlay = "prelude//apple/tools:make_vfsoverlay",
    selective_debugging_scrubber = "prelude//apple/tools/selective_debugging:tool",
    signing_context = ":no_binary",
    signing_context_tree_postprocessor = "prelude//apple/tools/signing_context_tree_postprocessor:signing_context_tree_postprocessor",
    split_arch_combine_dsym_bundles_tool = "prelude//apple/tools:split_arch_combine_dsym_bundles_tool",
    spm_packager = "prelude//apple/tools:spm_packager",
    static_archive_linker = "prelude//apple/tools:static_archive_linker",
    xcframework_maker = "prelude//apple/tools:xcframework_maker",
    visibility = ["PUBLIC"],
)

system_swift_toolchain(
    name = "swift",
    sdk_path = SDK_PATH,
    visibility = ["toolchains//..."],
)

system_apple_toolchain(
    name = "apple",
    platform_path = PLATFORM_PATH,
    sdk_name = "macosx",
    sdk_path = SDK_PATH,
    swift_toolchain = ":swift",
    visibility = ["toolchains//..."],
)
