load("//home:defs.bzl", "dotfiles")

dotfiles(
    name = "home",
    files = {
        "~/.config/direnv": glob([".config/direnv/*.toml"]),
        "~/.config/fish/functions": glob([".config/fish/functions/*.fish"]),
        "~/.config/ghostty": [".config/ghostty/config"],
        "~/.config/helix": glob([".config/helix/*.toml"]),
        "~/.config/jj": glob([".config/jj/*.toml"]),
        "~/.config/zed": glob([".config/zed/*.json"]),

        # binaries
        "~/.cache/installer/bin": [
            "//jj-pr:jj-pr",
            "//sprite-hacks/bin:git-remote-sprite",
            "//sprite-hacks/bin:jj-sprite-workspace",
        ],
    },
)
