version = "2026-06-01"

[[bin]]
platform = "aarch64-darwin"
url = "https://github.com/facebook/buck2/releases/download/2026-06-01/buck2-aarch64-apple-darwin.zst"
hash = "sha256-e4Hvd5PAuzq8HhSusRHgbyn6Kb2HF6NnUrMXugVz1TM="

[[bin]]
platform = "x86_64-linux"
url = "https://github.com/facebook/buck2/releases/download/2026-06-01/buck2-x86_64-unknown-linux-musl.zst"
hash = "sha256-q8vCwYKEomAuLgNt8p//akl1AJjTT1gfSzm7dnYzUXo="

[[bin]]
platform = "aarch64-linux"
url = "https://github.com/facebook/buck2/releases/download/2026-06-01/buck2-aarch64-unknown-linux-musl.zst"
hash = "sha256-3MhsXqulSCQ1EHHFqJZG8Uu5uexSJz+qU4Wog+tdm7Y="
