version = "2026.04.27.00"

[[bin]]
platform = "aarch64-darwin"
url = "https://github.com/facebookincubator/reindeer/releases/download/v2026.04.27.00/reindeer-aarch64-apple-darwin.zst"
hash = "sha256-MD1uyqUlvDiAsn4P9bnVxdi65XTlR6M75WF2VvAkuY8="

[[bin]]
platform = "x86_64-linux"
url = "https://github.com/facebookincubator/reindeer/releases/download/v2026.04.27.00/reindeer-x86_64-unknown-linux-musl.zst"
hash = "sha256-GULVYrhdfP7R9AyXWCmwQiL90NLz5lOTiWzBN1fi2rs="

[[bin]]
platform = "aarch64-linux"
url = "https://github.com/facebookincubator/reindeer/releases/download/v2026.04.27.00/reindeer-aarch64-unknown-linux-musl.zst"
hash = "sha256-0e1gLRbPBCkC28xK0tdmCZLtql0VGB6uEA2ey82vC84="
