version = "2026-04-15"

[[bin]]
platform = "aarch64-darwin"
url = "https://github.com/facebook/buck2/releases/download/2026-04-15/rust-project-aarch64-apple-darwin.zst"
hash = "sha256-K86j0E32w0DUwzpPT0NBUiL3rV4Ze8hzfbKDkpy9JXo="

[[bin]]
platform = "x86_64-linux"
url = "https://github.com/facebook/buck2/releases/download/2026-04-15/rust-project-x86_64-unknown-linux-musl.zst"
hash = "sha256-QaUhBP1yTZrpwz5qiNzjR/YDcgyF+XFDauc5GzQS0FY="

[[bin]]
platform = "aarch64-linux"
url = "https://github.com/facebook/buck2/releases/download/2026-04-15/rust-project-aarch64-unknown-linux-musl.zst"
hash = "sha256-fF3ZAXMLpHxpbtzYMSHlqKLVnVklBQBT5ANenYGk8AM="
