load("//deno:npm.bzl", "npm_package")
load("//deno:rules.bzl", "deno_binary")

deno_binary(
    name = "esbuild_build",
    main = "esbuild_build.js",
    permissions = ["env", "read", "run", "write"],
    unstable_features = ["detect-cjs"],
    npm_deps = ["root//third-party/npm/esbuild:esbuild"],
    visibility = ["//esbuild/..."],
)
