load("//esbuild:defs.bzl", "esbuild_plugin")

esbuild_plugin(
    name = "buck",
    source = "buck.ts",
    visibility = ["PUBLIC"],
)

esbuild_plugin(
    name = "css-stylesheet",
    source = "css-stylesheet.ts",
    visibility = ["PUBLIC"],
)

esbuild_plugin(
    name = "gzip-binary",
    source = "gzip-binary.ts",
    visibility = ["PUBLIC"],
)
