load(
    "@prelude//toolchains/go:go_bootstrap_toolchain.bzl",
    "go_bootstrap_distr",
    "go_bootstrap_toolchain",
)
load("@prelude//toolchains/go:go_toolchain.bzl", "go_distr", "go_toolchain")

# NOTE: we NEED to use a hermetic Go toolchain, because system_go_toolchain does
# not properly set GOROOT

http_archive(
    name = "archive_go1.25.7.darwin-arm64",
    sha256 = "ff18369ffad05c57d5bed888b660b31385f3c913670a83ef557cdfd98ea9ae1b",
    strip_prefix = "go",
    urls = ["https://go.dev/dl/go1.25.7.darwin-arm64.tar.gz"],
)

go_bootstrap_distr(
    name = "go_bootstrap_distr",
    go_os_arch = ("darwin", "arm64"),
    go_root = ":archive_go1.25.7.darwin-arm64",
)

go_bootstrap_toolchain(
    name = "go_bootstrap",
    env_go_arch = "arm64",
    env_go_os = "darwin",
    go_bootstrap_distr = ":go_bootstrap_distr",
    visibility = ["toolchains//..."],
)

go_distr(
    name = "go_distr",
    go_os_arch = ("darwin", "arm64"),
    go_root = ":archive_go1.25.7.darwin-arm64",
    version = "1.25.7",
)

go_toolchain(
    name = "go",
    env_go_arch = "arm64",
    env_go_os = "darwin",
    go_distr = ":go_distr",
    visibility = ["toolchains//..."],
)
