load(
    "@prelude//toolchains/go:go_bootstrap_toolchain.bzl",
    "go_bootstrap_distr",
    "go_bootstrap_toolchain",
)
load("@prelude//toolchains/go:go_toolchain.bzl", "go_distr", "go_toolchain")

# NOTE: we NEED to use a hermetic Go toolchain, because system_go_toolchain does
# not properly set GOROOT

http_archive(
    name = "archive_go1.26.5.darwin-arm64",
    sha256 = "efb87ff28af9a188d0536ef5d42e63dd52ba8263cd7344a993cc48dd11dedb6a",
    strip_prefix = "go",
    urls = ["https://go.dev/dl/go1.26.5.darwin-arm64.tar.gz"],
)

http_archive(
    name = "archive_go1.26.5.linux-amd64",
    sha256 = "5c2c3b16caefa1d968a94c1daca04a7ca301a496d9b086e17ad77bb81393f053",
    strip_prefix = "go",
    urls = ["https://go.dev/dl/go1.26.5.linux-amd64.tar.gz"],
)

go_bootstrap_distr(
    name = "go_bootstrap_distr",
    go_os_arch = select({
        "config//os:linux": ("linux", "amd64"),
        "config//os:macos": ("darwin", "arm64"),
    }),
    go_root = select({
        "config//os:linux": ":archive_go1.26.5.linux-amd64",
        "config//os:macos": ":archive_go1.26.5.darwin-arm64",
    }),
)

go_bootstrap_toolchain(
    name = "go_bootstrap",
    env_go_arch = select({
        "config//os:linux": "amd64",
        "config//os:macos": "arm64",
    }),
    env_go_os = select({
        "config//os:linux": "linux",
        "config//os:macos": "darwin",
    }),
    go_bootstrap_distr = ":go_bootstrap_distr",
    visibility = ["toolchains//..."],
)

go_distr(
    name = "go_distr",
    go_os_arch = select({
        "config//os:linux": ("linux", "amd64"),
        "config//os:macos": ("darwin", "arm64"),
    }),
    go_root = select({
        "config//os:linux": ":archive_go1.26.5.linux-amd64",
        "config//os:macos": ":archive_go1.26.5.darwin-arm64",
    }),
    version = "1.26.5",
)

go_toolchain(
    name = "go",
    env_go_arch = select({
        "config//os:linux": "amd64",
        "config//os:macos": "arm64",
    }),
    env_go_os = select({
        "config//os:linux": "linux",
        "config//os:macos": "darwin",
    }),
    go_distr = ":go_distr",
    visibility = ["toolchains//..."],
)
