load("//deno:rules.bzl", "deno_binary")

deno_binary(
    name = "protoc-gen-es",
    main = "protoc_gen_es.js",
    permissions = ["env", "read", "sys"],
    npm_deps = ["root//third-party/npm/@bufbuild/protoc-gen-es:protoc-gen-es"],
    visibility = ["//protobuf/..."],
)
